language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
  - wget https://phar.phpunit.de/phpunit-3.7.38.phar
  - chmod +x phpunit-3.7.38.phar
  - mv phpunit-3.7.38.phar phpunit

script: phpunit --coverage-text
